app: origin 
requestLimit: 1024
# apiPrefix: /api
listen: ":7001"

# cookie track key
track: jt


# redis 配置(pass从env中获取pass这个配置为密码，如果未配置则为空)
redis:
  # 可以配置为下面的形式，则从env中获取REDIS_URI对应的字符串来当redis连接串
  # uri: REDIS_URI
  # 配置redis连接串，如果有配置此参数，则忽略addr等参数
  # uri: redis://:pass@127.0.0.1:6379/?db=0&slow=200ms&maxProcessing=1000
  addr: 127.0.0.1:6379
  db: 0
  slow: 200ms
  maxProcessing: 1000

# postgres 配置 (pass从env中获取pass这个配置为密码，如果未配置则为空)
postgres:
  # 如果配置了uri连接串，直接使用
  # uri: host=127.0.0.1 port=5432 user=vicanso dbname=origin password=A123456 sslmode=disable
  host: 127.0.0.1
  port: 5432
  user: vicanso 
  dbname: origin
  password: A123456
  sslmode: disable
  slow: 1s
  maxQueryProcessing: 1000
  maxUpdateProcessing: 500

# influxdb 配置
influxdb:
  uri: http://127.0.0.1:9999
  bucket: origin
  org: bigtree
  token: YecVRjkFWQHQCq-Qs9NH7XZy8ApyAp9QfwVjqwQC_8bWmjsYRAfYTNveCswl1NPHS8reFoXELQBWKO27maa9tw==
  batchSize: 100
  flushInterval: 10s
  disabled: true 

# session的相关配置
session:
  path: /
  key: origin
  ttl: 240h

# key for sign cookie
keys:
  - cuttlefish
  - secret

location:
  baseURL: https://ip.npmtrend.com/

# mail相关配置
mail:
  host: smtp.office365.com
  port: 587
  user: tree.xie@outlook.com
  password: EMAIL_PASS

# 告警接收邮件列表
alarm:
  receiver:
  - tree.xie@outlook.com

# minio配置
minio:
  endpoint: 127.0.0.1:9000
  accessKeyID: origin
  secretAccessKey: test123456
  ssl: false

# tiny服务的配置
tiny:
  host: 127.0.0.1
  port: 6002