# production 生产环境中使用的相关配置
redis:
  uri: REDIS_URI

# postgres 配置 (pass从env中获取pass这个配置为密码，如果未配置则为空)
postgres:
  uri: PG_URI

# influxdb 配置
influxdb:
  uri: http://172.18.109.188:9999
  token: dd6CeAtuD51rcor5tYnkxP0NXSTuxbrgd31sc-U-j-hUty-loKg_Ad4M9zT_0svhMl3SylzJE089rS7j6ijtyw==

minio:
  endpoint: 172.18.109.188:9000
  secretAccessKey: iAyeiXLVmuqOOhKvYHOR

# tiny服务的配置
tiny:
  host: 172.18.109.188
  port: 7002