# test 测试环境使用的相关配置
# redis 配置(pass从env中获取pass这个配置为密码，如果未配置则为空)
redis:
  uri: REDIS_URI

# postgres 配置 (pass从env中获取pass这个配置为密码，如果未配置则为空)
postgres:
  uri: PG_URI

minio:
  endpoint: 192.168.1.6:9000
  secretAccessKey: Origin0517
